version: '3'
services:
  ## EUREKA SERVER
  eureka-server:
    build: eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761
    environment:
      EUREKA_USER: eureka
      EUREKA_PASSWORD: password  
    restart: always
    networks:
      - local_network

    

  ### F1 Service
  f1-service:
    build: f1-service
    container_name: f1-service
    ports:
      - 8083:8083
    depends_on:
      - eureka-server
      - db-f1
      - keycloak-server
    environment:
      DB_USERNAME: freddy
      DB_PASSWORD: Test123
      EUREKA_USER: eureka
      EUREKA_PASSWORD: password
      REALM_NAME: http://keycloak-server:9090/realms/microservices-motorsport-predictor-realm
      REALM_CERTS: http://keycloak-server:9090/realms/microservices-motorsport-predictor-realm/protocol/openid-connect/certs
    restart: always
    networks:
      - local_network
    

  ### Users Service
  users-service:
    build: users-service
    container_name: users-service
    ports:
      - 8081:8081
    depends_on:
      - eureka-server
      - db-users
      - keycloak-server
    environment:
      DB_USERNAME: freddy
      DB_PASSWORD: Test123
      EUREKA_USER: eureka
      EUREKA_PASSWORD: password
      REALM_NAME: http://keycloak-server:9090/realms/microservices-motorsport-predictor-realm
      REALM_CERTS: http://keycloak-server:9090/realms/microservices-motorsport-predictor-realm/protocol/openid-connect/certs
    restart: always
    networks:
      - local_network

  ### Predictions Service
  predictions-service:
    build: predictions-service
    container_name: predictions-service
    ports:
      - 8082:8082
    depends_on:
      - eureka-server
      - db-predictions
      - keycloak-server
    environment:
      DB_USERNAME: freddy
      DB_PASSWORD: Test123
      EUREKA_USER: eureka
      EUREKA_PASSWORD: password
      REALM_CERTS: http://keycloak-server:9090/realms/microservices-motorsport-predictor-realm/protocol/openid-connect/certs
    restart: always
    networks:
      - local_network

  ### Notification Service
  notification-service:
    build: notification-service
    container_name: notification-service
    ports:
      - 8084:8084
    depends_on:
      - eureka-server
    environment:
      EUREKA_USER: eureka
      EUREKA_PASSWORD: password  
      MAIL_USERNAME: ferreirafreddy39@gmail.com
      MAIL_PASSWORD: arku qlqw zqpg ntjj 
    restart: always
    networks:
      - local_network

  ### Gateway Service
  gateway-server:
    build: gateway-server
    container_name: gateway-server
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - keycloak-server
    environment:
      EUREKA_USER: eureka
      EUREKA_PASSWORD: password  
      KC_CLIENT_ID: microservices-motorsport-client
      KC_CLIENT_SECRET: cKqUA6aHPFAU4kaZjXe7FY1mw1VwVxxh
      REALM_NAME: http://keycloak-server:9090/realms/microservices-motorsport-predictor-realm
      REALM_CERTS: http://keycloak-server:9090/realms/microservices-motorsport-predictor-realm/protocol/openid-connect/certs
      
    restart: always
    networks:
      - local_network
    

  ### MySQL database for users
  db-users:
    container_name: db-users
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_users
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db-users:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    expose:
      - 3306
    networks:
      - local_network


  ### MySQL database for predictions
  db-predictions:
    container_name: db-predictions
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_predictions
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db-predictions:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306
    expose:
      - 3306
    networks:
      - local_network

  ### Mysql database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_keycloak
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    expose:
      - 3306
    networks:
      - local_network

  ### MySQL database for F1 service
  db-f1:
    container_name: db-f1
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_f1
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db-f1:/docker-entrypoint-initdb.d
    ports:
      - 3310:3306
    expose:
      - 3306
    networks:
      - local_network

  ### Keycloak
  keycloak-server:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:25.0.1
    command: -v start-dev --import-realm
    ports:
      - 9090:9090
    expose:
      - 9090
    depends_on:
      - db-keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db-keycloak:3306/db_keycloak
      KC_DB_USERNAME: freddy
      KC_DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak-server
      KC_HTTP_PORT: 9090
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_URL: http://localhost:9090
    volumes:
      - ./imports:/opt/keycloak/data/import
    networks:
      - local_network


  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - local_network

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - local_network

networks:
  local_network:
    driver: bridge