version: '3'
services:
  ### MySQL database for users
  db-users:
    container_name: db-users
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_users
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    expose:
      - 3306


  ### MySQL database for predictions
  db-predictions:
    container_name: db-predictions
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_predictions
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    expose:
      - 3306

  ### Mysql database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_keycloak
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    expose:
      - 3306

  ### MySQL database for F1 service
  db-f1:
    container_name: db-f1
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_f1
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3306
    expose:
      - 3306

  ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    command: ["start-dev"]
    ports:
      - 9090:9090
    expose:
      - 9090
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 3309
      DB_USER: freddy
      DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 9090