version: '3'
services:
  ### MySQL database for users
  db-users:
    container_name: db-users
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_users
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    expose:
      - 3306


  ### MySQL database for predictions
  db-predictions:
    container_name: db-predictions
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_predictions
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    expose:
      - 3306

  ### Mysql database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_keycloak
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    expose:
      - 3306
    networks:
      - local_network

  ### MySQL database for F1 service
  db-f1:
    container_name: db-f1
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_motorsport_predictor_f1
      MYSQL_USER: freddy
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3306
    expose:
      - 3306

  ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    command: ["start-dev"]
    ports:
      - 9090:9090
    expose:
      - 9090
    depends_on:
      - db-keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db-keycloak:3306/db_keycloak
      KC_DB_USERNAME: freddy
      KC_DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 9090
    networks:
      - local_network


  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ##MailHog
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

networks:
  local_network:
    driver: bridge